// <auto-generated />
using System;
using FyersCopyTrading.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopyTrading.Migrations
{
    [DbContext(typeof(CopyTradingDbContext))]
    [Migration("20261003025236_FixAccountBalance")]
    partial class FixAccountBalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FyersCopyTrading.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = "P001",
                            AccountName = "Chandana (Parent)",
                            AccountType = "PARENT",
                            Balance = 1000000.00m,
                            CreatedAt = new DateTime(2026, 10, 3, 8, 22, 35, 766, DateTimeKind.Local).AddTicks(9802)
                        },
                        new
                        {
                            AccountId = "C001",
                            AccountName = "Ramu (Child 1)",
                            AccountType = "CHILD",
                            Balance = 500000.00m,
                            CreatedAt = new DateTime(2026, 10, 3, 8, 22, 35, 766, DateTimeKind.Local).AddTicks(9815)
                        },
                        new
                        {
                            AccountId = "C002",
                            AccountName = "Seenu (Child 2)",
                            AccountType = "CHILD",
                            Balance = 500000.00m,
                            CreatedAt = new DateTime(2026, 10, 3, 8, 22, 35, 766, DateTimeKind.Local).AddTicks(9816)
                        },
                        new
                        {
                            AccountId = "C003",
                            AccountName = "Priya (Child 3)",
                            AccountType = "CHILD",
                            Balance = 500000.00m,
                            CreatedAt = new DateTime(2026, 10, 3, 8, 22, 35, 766, DateTimeKind.Local).AddTicks(9817)
                        },
                        new
                        {
                            AccountId = "C004",
                            AccountName = "Arjun (Child 4)",
                            AccountType = "CHILD",
                            Balance = 500000.00m,
                            CreatedAt = new DateTime(2026, 10, 3, 8, 22, 35, 766, DateTimeKind.Local).AddTicks(9818)
                        });
                });

            modelBuilder.Entity("FyersCopyTrading.Models.AccountMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingId"));

                    b.Property<string>("ChildAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ParentAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("QtyMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MappingId");

                    b.HasIndex("ChildAccountId");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("AccountMappings");

                    b.HasData(
                        new
                        {
                            MappingId = 1,
                            ChildAccountId = "C001",
                            IsActive = true,
                            ParentAccountId = "P001",
                            QtyMultiplier = 1.0m
                        },
                        new
                        {
                            MappingId = 2,
                            ChildAccountId = "C002",
                            IsActive = true,
                            ParentAccountId = "P001",
                            QtyMultiplier = 0.5m
                        },
                        new
                        {
                            MappingId = 3,
                            ChildAccountId = "C003",
                            IsActive = true,
                            ParentAccountId = "P001",
                            QtyMultiplier = 2.0m
                        },
                        new
                        {
                            MappingId = 4,
                            ChildAccountId = "C004",
                            IsActive = true,
                            ParentAccountId = "P001",
                            QtyMultiplier = 1.5m
                        });
                });

            modelBuilder.Entity("FyersCopyTrading.Models.ChildOrder", b =>
                {
                    b.Property<int>("ChildOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildOrderId"));

                    b.Property<string>("ChildAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReplicatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChildOrderId");

                    b.ToTable("ChildOrders");
                });

            modelBuilder.Entity("FyersCopyTrading.Models.ParentOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("ParentOrders");
                });

            modelBuilder.Entity("FyersCopyTrading.Models.AccountMapping", b =>
                {
                    b.HasOne("FyersCopyTrading.Models.Account", "ChildAccount")
                        .WithMany()
                        .HasForeignKey("ChildAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FyersCopyTrading.Models.Account", "ParentAccount")
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildAccount");

                    b.Navigation("ParentAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
